= Ike Prow Plugins
:asciidoctor-source: https://raw.githubusercontent.com/arquillian/ike-prow-plugins/master/docs
:numbered:
:sectlink:
:sectanchors:
:sectid:
:source-language: java
:source-highlighter: coderay
:sectnums:
:icons: font
ifndef::generated-doc[]
:toc: macro
:toclevels: 1
endif::generated-doc[]
ifdef::generated-doc[]
:toc: left
:toclevels: 2
endif::generated-doc[]
:data-uri:
:imagesdir: docs

ifndef::generated-doc[]

Welcome in PR automation plugins Arquillian project. These plugins are based on link:https://github.com/kubernetes/test-infra/tree/master/prow[Prow] sub project of
Kubernetes Test Infrastructure.


[discrete]
endif::generated-doc[]

== Prerequisites

You need to have following packages in place:

* `git`
* `make`
* `go` (`>= v1.9.4`)
* link:https://glide.sh/[`glide`] for dependency management
* link:https://github.com/alecthomas/gometalinter[`gometalinter`]

Assuming that you have all the link:https://golang.org/doc/install[Golang prerequisites] in place (such as `$GOPATH`), clone the repository first:

[source,bash]
----
$ git clone https://github.com/arquillian/ike-prow-plugins $GOPATH/src/github.com/arquillian/ike-prow-plugins
----

NOTE: Have a look how link:https://github.com/moovweb/gvm[Go Version Manager] can help you simplifying configuration and
management of different versions of Go.

NOTE: You can also use link:https://raw.githubusercontent.com/arquillian/ike-prow-plugins/master/setup.sh[`setup.sh`] which takes care of all of the above. Simply execute +
`$ curl -sSL https://git.io/vxnSk | bash` +
and you are all set.


ifndef::generated-doc[]

[discrete]
== Documentation

The complete documentation can be found at http://arquillian.org/ike-prow-plugins.

You can also generate it locally. All you need to have in place is https://docs.docker.com/engine/installation/[Docker].
Simply execute

```
$ ./.asciidoctor/generate.sh
```
and you are set. You will find generated documentation in the `gh-pages` folder.

On Linux you can combine it with following command:

```
./.asciidoctor/generate.sh && xdg-open gh-pages/index.html &>/dev/null
```

This will generate the documentation and open it in the browser.
endif::generated-doc[]

ifdef::generated-doc[]

include::{asciidoctor-source}/getting_started.adoc[]
include::{asciidoctor-source}/plugins.adoc[]

endif::generated-doc[]