== Work In Progress Plugin

This plugin can help reviewers with focusing on work that really matters so they don't need to spend time with Pull Requests that are still in progress unless they were requested to do partial reviews.

The plugin checks the PR for the presence of "work in progress" prefix in title and the GitHub label to manage the status of the PR in progress and or manage the addition/deletion of the label or the prefix respectively as described in the following cases:

****
**Case 1:** The PR is has a "work in progress" label but the "work in progress" prefix is missing in the title.

* The PR status is marked as **Failure** and the title is left as it is.

**Case 2:** The PR title contains the "work in progress" prefix but no "work in progress" label is included.

* The PR status is marked as **Failure** and the "work in progress" label is added automatically.

**Case 3:** The PR title is updated and "work in progress" prefix is removed.

* The PR status is changed to **Success** and the "work in progress" label is removed automatically.

**Case 4:** The PR is updated and the "work in progress" label is removed.

* The PR status is changed to **Success** and the "work in progress" prefix is removed automatically.
****

where the PR title's "work in progress" prefix can have any of the default prefixes (`WIP`, `DO NOT MERGE`, `DON'T MERGE`, `WORK-IN-PROGRESS` with any combinations of the flavors such as `( )`, `[ ]`, `{ }`, `! !`,`* *`, etc...) or any of the user configured prefixes as described below (non-case sensitive) and the "work in progress" GitHub label can have the default value (`const:pkg/plugin/work-in-progress/configuration.go[name="DefaultLabel"]`) or any other user configured value as described below as valid values.

=== Plugin Configuration [[work-in-progress-config]]

To configure Work In Progress plugin place `work-in-progress.yml` (or `work-in-progress.yaml`) file inside of the directory `.ike-prow/` in your project and use properties described below.

.work-in-progress.yaml
[source, yml, indent=0]
----
include::../../pkg/plugin/work-in-progress/test_fixtures/github_calls/work-in-progress.yml[]
----

<1> Defines set of custom-prefixes which will be used to match titles prefixes in changeset and determine if Pull Requests are still in progress.
<2> Allows you to decide if you want to combine your patterns with the list (`WIP`, `DO NOT MERGE`, `DON'T MERGE`, `WORK-IN-PROGRESS`) of predefined defaults (`true` by default).
<3> Defines the custom name to be used for the GitHub label for the "work in progress pull request" (`const:pkg/plugin/work-in-progress/configuration.go[name="DefaultLabel"]` by default).

=== Status details

In this section, you can find status details description applicable for each state of the `work-in-progress` plugin.

include::{asciidoctor-source}/chapters/status/work-in-progress/success/wip-success.adoc[leveloffset=1]
include::{asciidoctor-source}/chapters/status/work-in-progress/failure/wip-failed.adoc[leveloffset=1]
