kind: Template
apiVersion: v1
parameters:
- name: REGISTRY
  required: true
  value: gcr.io
- name: DOCKER_REPO
  required: true
  value: k8s-prow
- name: VERSION
  value: v20180316-93ade3390
  required: true
- name: HOOK_HOSTNAME
  value: ""
objects:
  - kind: Deployment
    apiVersion: extensions/v1beta1
    metadata:
      name: hook
      labels:
        app: hook
        type: prow-core
    spec:
      replicas: 1
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
      template:
        metadata:
          labels:
            app: hook
            type: prow-core
        spec:
          terminationGracePeriodSeconds: 180
          containers:
          - name: hook
            image: ${REGISTRY}/${DOCKER_REPO}/hook:${VERSION}
            imagePullPolicy: Always
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"
            args:
            - --dry-run=false
            ports:
              - name: http
                containerPort: 8888
            volumeMounts:
            - name: hmac
              mountPath: /etc/webhook
              readOnly: true
            - name: oauth
              mountPath: /etc/github
              readOnly: true
            - name: config
              mountPath: /etc/config
              readOnly: true
            - name: plugins
              mountPath: /etc/plugins
              readOnly: true
          volumes:
          - name: hmac
            secret:
              secretName: hmac-token
          - name: oauth
            secret:
              secretName: oauth-token
          - name: config
            configMap:
              name: config
          - name: plugins
            configMap:
              name: plugins
  - kind: Service
    apiVersion: v1
    metadata:
      name: hook
    spec:
      selector:
        app: hook
      ports:
      - port: 8888
      type: NodePort
  - kind: Route
    apiVersion: v1
    metadata:
      name: hook
    spec:
      host: ""
      to:
        kind: Service
        name: hook