kind: Template
apiVersion: v1
parameters:
- name: REGISTRY
  required: true
  value: quay.io
- name: DOCKER_REPO
  required: true
  value: openshiftio
- name: PROJECT_NAME
  required: true
  value: ike-prow-plugins
- name: PLUGIN_NAME
  required: true
- name: IMAGE_TAG
  required: true
  value: latest
objects:
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${PLUGIN_NAME}
      labels:
        app: ${PLUGIN_NAME}
        type: ike-plugin
        version: ${IMAGE_TAG}
    spec:
      replicas: 1
      triggers:
        - type: ConfigChange
      strategy:
        type: Rolling
        rollingParams:
          intervalSeconds: 1
          updatePeriodSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
      template:
        metadata:
          labels:
            app: ${PLUGIN_NAME}
            type: ike-plugin
        spec:
          terminationGracePeriodSeconds: 180
          containers:
          - name: ${PLUGIN_NAME}
            image: ${REGISTRY}/${DOCKER_REPO}/${PROJECT_NAME}-${PLUGIN_NAME}:${IMAGE_TAG}
            imagePullPolicy: Always
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"
            env:
              - name: VERSION
                value: ${IMAGE_TAG}
            args:
            - --dry-run=false
            ports:
              - name: http
                containerPort: 8888
              - name: pmcd
                containerPort: 44321
            volumeMounts:
            - name: hmac
              mountPath: /etc/webhook
              readOnly: true
            - name: oauth
              mountPath: /etc/github
              readOnly: true
            - name: plugins
              mountPath: /etc/plugins
              readOnly: true
            - name: sentry-dsn
              mountPath: /etc/sentry-dsn
              readOnly: true
            readinessProbe:
              httpGet:
                path: /version
                port: 8888
            livenessProbe:
              httpGet:
                path: /version
                port: 8888            
          volumes:
          - name: hmac
            secret:
              secretName: ike-prow-plugins-hmac-token
          - name: oauth
            secret:
              secretName: ike-prow-plugins-oauth-token
          - name: sentry-dsn
            secret:
              secretName: ike-prow-plugins-sentry-dsn
          - name: plugins
            configMap:
              name: ike-prow-plugins-plugins
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${PLUGIN_NAME}
    spec:
      selector:
        app: ${PLUGIN_NAME}
      ports:
      - port: 80
        targetPort: 8888
      type: NodePort
  - kind: Service
    apiVersion: v1
    metadata:
      name: pmcd-${PLUGIN_NAME}
    spec:
      selector:
        app: ${PLUGIN_NAME}
      ports:
      - port: 44321
        targetPort: 44321
      type: NodePort
