kind: Template
apiVersion: v1
parameters:
- name: REGISTRY
  required: true
  value: docker.io
- name: DOCKER_REPO
  required: true
  value: arquillian
- name: PLUGIN_NAME
  required: true
- name: VERSION
  required: true
objects:
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${PLUGIN_NAME}
      labels:
        app: ${PLUGIN_NAME}
        type: ike-plugin
        version: ${VERSION}
    spec:
      replicas: 1
      triggers:
        - type: ConfigChange
      strategy:
        type: Rolling
        rollingParams:
          intervalSeconds: 1
          updatePeriodSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
      template:
        metadata:
          labels:
            app: ${PLUGIN_NAME}
            type: ike-plugin
        spec:
          terminationGracePeriodSeconds: 180
          containers:
          - name: ${PLUGIN_NAME}
            image: ${REGISTRY}/${DOCKER_REPO}/${PLUGIN_NAME}:${VERSION}
            imagePullPolicy: Always
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"
            env:
              - name: VERSION
                value: ${VERSION}
            args:
            - --dry-run=false
            ports:
              - name: http
                containerPort: 8888
            volumeMounts:
            - name: hmac
              mountPath: /etc/webhook
              readOnly: true
            - name: oauth
              mountPath: /etc/github
              readOnly: true
            - name: plugins
              mountPath: /etc/plugins
              readOnly: true
            - name: sentry-dsn
              mountPath: /etc/sentry-dsn
              readOnly: true
            readinessProbe:
              httpGet:
                path: /version
                port: 8888
              initialDelaySeconds: 5
              periodSeconds: 5
            livenessProbe:
              httpGet:
                path: /version
                port: 8888
              initialDelaySeconds: 5
              periodSeconds: 5  
          volumes:
          - name: hmac
            secret:
              secretName: hmac-token
          - name: oauth
            secret:
              secretName: oauth-token
          - name: sentry-dsn
            secret:
              secretName: sentry-dsn
          - name: plugins
            configMap:
              name: plugins
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${PLUGIN_NAME}
    spec:
      selector:
        app: ${PLUGIN_NAME}
      ports:
      - port: 80
        targetPort: 8888
      type: NodePort  