kind: Template
apiVersion: v1
parameters:
- name: REGISTRY
  required: true
  value: docker.io
- name: DOCKER_REPO
  required: true
  value: bartoszmajsak
- name: PLUGIN_NAME
  required: true
- name: VERSION
  value: latest
  required: true
objects:
  - kind: Deployment
    apiVersion: extensions/v1beta1
    metadata:
      name: ${PLUGIN_NAME}
      labels:
        app: ${PLUGIN_NAME}
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: ${PLUGIN_NAME}
        spec:
          terminationGracePeriodSeconds: 180
          containers:
          - name: ${PLUGIN_NAME}
            image: ${REGISTRY}/${DOCKER_REPO}/${PLUGIN_NAME}:${VERSION}
            imagePullPolicy: Always
            args:
            - --dry-run=false
            ports:
              - name: http
                containerPort: 8888
            volumeMounts:
            - name: hmac
              mountPath: /etc/webhook
              readOnly: true
            - name: oauth
              mountPath: /etc/github
              readOnly: true
            - name: plugins
              mountPath: /etc/plugins
              readOnly: true
            - name: sentry-dsn
              mountPath: /etc/sentry-dsn
              readOnly: true
          volumes:
          - name: hmac
            secret:
              secretName: hmac-token
          - name: oauth
            secret:
              secretName: oauth-token
          - name: sentry-dsn
            secret:
              secretName: sentry-dsn
          - name: plugins
            configMap:
              name: plugins
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${PLUGIN_NAME}
    spec:
      selector:
        app: ${PLUGIN_NAME}
      ports:
      - port: 80
        targetPort: 8888
      type: NodePort