
== Plugins

=== Configuration

In order to enable certain plugins for your repository or organization, you should edit `plugins.yaml` file adding:

[source,yml]
----
include::../plugins.yaml[tag="external_plugins"]
----
<1> The `test-keeper` plugin will be applied to specified repository. You can also specify plugins only for the whole
organization. Be aware however, that adding an external plugin both to the repository and its organization link:https://github.com/kubernetes/test-infra/blob/7de525b1f6943e5d08d9a127b0b668cec404c665/prow/plugins/plugins_test.go#L143[will result in an error].
<2> You can limit events dispatched by hook to your plugin.

==== Creating custom plugin hint messages

Customized comment message can be configured as `plugin hint` to express suggestions regarding the plugin's intented behavior. + 
Eg. Configuring `plugin hint` for the `test-keeper` plugin adds comment message to the Pull Request when no test is found. 

By default, the custom plugin hint message is loaded from a file `PLUGINNAME_HINT.md` located in `.ike-prow/` directory (if present). The `PLUGINNAME` is a name of the plugin you want to set the custom hint message for, so for example `.ike-prow/test-keeper_hint.md`.
It is also possible to set other location of the hint file or directly the content of the message by editing plugin's configuration file (eg. test-keeper.yaml) and adding the `plugin_hint` property there:

.test-keeper.yaml
[source, yml, indent=0]
----
plugin_hint: plugins/test-keeper_hint.md
----

The `plugin_hint` property can either have an inline string directly written inside of the config file or another file with case insensitive filename PLUGINNAME_HINT.md that contains the hint. The location of the file can be set by either a relative path or an absolute URL.

==== GitHub settings [[gh-settings]]

You will need two secrets to be able to integrate with GitHub. The `config/hmac.token` file should contain the token that
you give to GitHub for validating webhooks. You can generate it using any reasonable randomness-generator, for example
link:http://random.org[random.org].

The `config/oauth.token` is an OAuth2 token that has read and write access to the GitHub account. Generate it from
link:https://github.com/settings/tokens/new[here]. Depending on your plugin needs the scopes might vary,
but it is important to have following scopes enabled: `admin:org_hook` and `admin:repo_hook`.

NOTE: Both of these files are ignored by git (see `.gitignore`) so you can keep them in your repository, as some `make`
targets rely on them.

==== Setting up the web hook [[webhook]]

In order to setup webhook for your repository go to `https://github.com/{org}/{repo}/settings/hooks/new` and provide:

* payload URL
* content type needs to be `application-json`
* secret the same as defined in `config/hmac.token` file
* customize types of hooks you would like to receive (or use all to start)

For hints how to test web hook against your local setup head over to <<testing-hooks>> section.

NOTE: More details about GitHub hooks can be found in the link:https://developer.github.com/webhooks/[official developer documentation].

include::{asciidoctor-source}/fragments/test-keeper.adoc[leveloffset=1]
include::{asciidoctor-source}/fragments/work-in-progress.adoc[leveloffset=1]

=== Trigger Plugins on Demand
In order to trigger plugin on demand, just add `run plugin-name`(e.g. `run test-keeper`) comment on pull request. If you want to trigger only specific set of plugins, you can trigger it by adding comment `run plugin-A plugin-B`(e.g. `run test-keeper work-in-progress`).
However if you want to run all plugins configured for your repository, just add `/run all` comment on pull request.
